Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/jupyter_cache/executors/utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "/usr/local/lib/python3.7/site-packages/nbclient/client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/local/lib/python3.7/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/usr/local/lib/python3.7/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/usr/local/Cellar/python@3.7/3.7.13_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.7/site-packages/nbclient/client.py", line 554, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "/usr/local/lib/python3.7/site-packages/nbclient/client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/usr/local/lib/python3.7/site-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import numpy as np
data = [0, 1, 3, 2, 4, 5, 7, 6, 8, 9, 10, 11]
print("Median (odd number of observations):", np.median(data))
print(Series(data).quantile(0.50))

data = [0, 1, 3, 2, 4, 5, 7, 6, 8, 9, 10, 11, 12]
print("Median (odd number of observations):", np.median(data))
print(Series(data).quantile(0.50))
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
[0;32m<ipython-input-9-7026e5c5875d>[0m in [0;36m<module>[0;34m[0m
[1;32m      2[0m [0mdata[0m [0;34m=[0m [0;34m[[0m[0;36m0[0m[0;34m,[0m [0;36m1[0m[0;34m,[0m [0;36m3[0m[0;34m,[0m [0;36m2[0m[0;34m,[0m [0;36m4[0m[0;34m,[0m [0;36m5[0m[0;34m,[0m [0;36m7[0m[0;34m,[0m [0;36m6[0m[0;34m,[0m [0;36m8[0m[0;34m,[0m [0;36m9[0m[0;34m,[0m [0;36m10[0m[0;34m,[0m [0;36m11[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m
[1;32m      3[0m [0mprint[0m[0;34m([0m[0;34m"Median (odd number of observations):"[0m[0;34m,[0m [0mnp[0m[0;34m.[0m[0mmedian[0m[0;34m([0m[0mdata[0m[0;34m)[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 4[0;31m [0mprint[0m[0;34m([0m[0mSeries[0m[0;34m([0m[0mdata[0m[0;34m)[0m[0;34m.[0m[0mquantile[0m[0;34m([0m[0;36m0.50[0m[0;34m)[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      5[0m [0;34m[0m[0m
[1;32m      6[0m [0mdata[0m [0;34m=[0m [0;34m[[0m[0;36m0[0m[0;34m,[0m [0;36m1[0m[0;34m,[0m [0;36m3[0m[0;34m,[0m [0;36m2[0m[0;34m,[0m [0;36m4[0m[0;34m,[0m [0;36m5[0m[0;34m,[0m [0;36m7[0m[0;34m,[0m [0;36m6[0m[0;34m,[0m [0;36m8[0m[0;34m,[0m [0;36m9[0m[0;34m,[0m [0;36m10[0m[0;34m,[0m [0;36m11[0m[0;34m,[0m [0;36m12[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m

[0;31mNameError[0m: name 'Series' is not defined
NameError: name 'Series' is not defined

